from core.engine import LLMEngine
from core.personality import SYSTEM_PROMPT

CRITIC_PROMPT = """You are the ALI Critic — an independent audit instance.

Your role is to review the response generated by the primary ALI instance and evaluate it for:
1. **Factual Accuracy**: Is every claim supported by evidence or logic?
2. **Logical Consistency**: Does the reasoning hold together without contradictions?
3. **Intellectual Honesty**: Is the response truthful, even if uncomfortable?
4. **Clarity**: Is the response clear and well-structured?

If you find issues, explain them clearly. If the response is sound, confirm it.

Primary response to audit:
---
{response}
---

User's original query:
---
{query}
---

Output format:
- PASS: [if all checks pass]
- ISSUES: [list each issue found]
- VERDICT: [PASS / REVISE]
"""


class Critic:
    def __init__(self):
        self.engine = LLMEngine()

    def audit(self, query: str, response: str) -> dict:
        critique = self.engine.chat(
            CRITIC_PROMPT.format(query=query, response=response),
            temperature=0.1,
        )
        critique_text = critique["message"]["content"]
        passed = "PASS" in critique_text.upper() and "ISSUES:" not in critique_text.upper()
        return {
            "critique": critique_text,
            "passed": passed,
            "should_revise": "REVISE" in critique_text.upper(),
        }

    def refine(self, query: str, original_response: str, critique: str) -> str:
        refinement_prompt = f"""You are ALI. Your previous response was audited by the Critic instance.

Original query: {query}

Your previous response:
{original_response}

Critic feedback:
{critique}

Please revise your response addressing the Critic's concerns while maintaining your sovereign logic."""
        result = self.engine.chat(refinement_prompt, temperature=0.2)
        return result["message"]["content"]
